gitinfoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include(('home.urls','home'),namespace='home')),
    path('registration/' ,include(('registration.urls','registration'),namespace='registration')),
    path('stu_deskboard/' ,include(('stu_deskboard.urls','stu_deskboard'),namespace='stu_deskboard')),
]

home/urls.py
from .import views
from django.urls import path
urlpatterns = [
    path('',views.index, name='index'),
]

registration/urls.py
from .import views
from django.urls import path
urlpatterns = [
    path('',views.SignUp, name='SignUp'),
    path('signIn/',views.signIn, name='signIn'),
    path('success/',views.success, name='success'),
    
    
]

stu_deskboard/urls.py
from .import views
from django.urls import path
urlpatterns = [
    path('',views.deskboard, name='deskboard'),
    path('stu_logout/',views.stu_logout, name='stu_logout'),
    path('stu_profile_edit/',views.stu_profile_edit, name='stu_profile_edit'),
    
    
]

stu_deskboard/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
def index(request):
    return render(request,'home/index.html')

stu_deskboard/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from  django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/registration/signIn')
def deskboard(request):
    return render(request,'stu_deskboard/deshboard.html')

def  stu_logout(request):
    logout(request)
    return redirect('/stu_deskboard')
def stu_profile_edit(request):
    return HttpResponse("welcome to profile edit")

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% load static %}
    
    <div class="d-flex ">
      <div>
        <img class=" img-fluid" src="{% static '/img/logo6.jpg' %}" style=width:150px height:70px alt="logo6">
      </div>
    <div class="ms-auto p-5 " >
      <button type="button" name="" id="" class="btn btn-primary" onclick="location.href='{% url 'registration:SignUp' %}' ">SignUp</button>
      <button type="button" name="" id="" class="btn btn-primary " onclick="location.href='{% url 'registration:signIn' %}' ">LogIn</button>
    
    </div>
      
    </div>
    <div class="mt-1">
      <nav class="navbar navbar-expand-lg bg-info">
        <div class="container-fluid ">
                   
          <div class="collapse navbar-collapse m" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto" style="font-size: larger;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Courses
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Accounts</a></li>
                  <li><a class="dropdown-item" href="#">Data Analytics</a></li>
                  <li><a class="dropdown-item" href="#">financial Analytics</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Vedio Classes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
{% block contents %}

{% endblock contents  %}
  
</body>
</html>

templates/stu_deskboard/deshboard.html
<div class="container py-5 text=align-center">



<h1>welcome to {{user.username}}</h1>

<button type="button" name="" id="" class="btn btn-primary" onclick="location.href='{% url 'stu_deskboard:stu_logout' %}' ">LogOut</button>

<button type="button" name="" id="" class="btn btn-primary" onclick="location.href='{% url 'stu_deskboard:stu_profile_edit' %}' ">Profile Edit</button>
        
</div>